// api/profiles.js — Load pre-computed play-by-play analytics profiles
// These are generated by the Python analysis pipeline from nflfastR data.

const PROFILE_URLS = {
  qb: 'data/qb_profiles.json',
  receiver: 'data/receiver_profiles.json',
  rb: 'data/rb_profiles.json',
  team: 'data/team_profiles.json',
};

const profileCache = {};

async function fetchProfile(key) {
  if (profileCache[key]) return profileCache[key];
  try {
    const res = await fetch(PROFILE_URLS[key]);
    if (!res.ok) return {};
    const data = await res.json();
    profileCache[key] = data;
    return data;
  } catch (e) {
    console.warn(`Failed to load ${key} profiles:`, e);
    return {};
  }
}

export async function loadAllProfiles() {
  const [qb, receiver, rb, team] = await Promise.all([
    fetchProfile('qb'),
    fetchProfile('receiver'),
    fetchProfile('rb'),
    fetchProfile('team'),
  ]);
  return { qb, receiver, rb, team };
}

// Convert "Patrick Mahomes" (Sleeper) to "P.Mahomes" (nflfastR)
function toNflfastrName(fullName) {
  if (!fullName) return '';
  const parts = fullName.trim().split(/\s+/);
  if (parts.length < 2) return fullName;
  return parts[0].charAt(0) + '.' + parts[parts.length - 1];
}

function findInProfileSet(data, playerName) {
  if (!data) return null;
  // Try exact match first (handles edge cases)
  if (data[playerName]) return data[playerName];
  // Try nflfastR format: "P.Mahomes"
  const nflName = toNflfastrName(playerName);
  if (data[nflName]) return data[nflName];
  // Try last-name match as fallback (for names like "Amon-Ra St. Brown")
  const lastName = playerName.split(/\s+/).pop();
  for (const [key, profile] of Object.entries(data)) {
    if (key.endsWith('.' + lastName) || key.endsWith(' ' + lastName)) {
      return profile;
    }
  }
  return null;
}

export function getPlayerProfile(profiles, playerName, position) {
  if (!profiles || !playerName) return null;
  let found = null;
  // Try position-specific set first
  if (position === 'QB') found = findInProfileSet(profiles.qb, playerName);
  else if (position === 'WR' || position === 'TE') found = findInProfileSet(profiles.receiver, playerName);
  else if (position === 'RB') found = findInProfileSet(profiles.rb, playerName);

  if (found) {
    const type = position === 'QB' ? 'qb' : position === 'RB' ? 'rb' : 'receiver';
    return { ...found, profileType: type };
  }
  // Fallback: search all profile sets
  for (const [type, data] of Object.entries(profiles)) {
    if (type === 'team') continue;
    const match = findInProfileSet(data, playerName);
    if (match) return { ...match, profileType: type };
  }
  return null;
}

export function getTeamProfile(profiles, teamAbbr) {
  if (!profiles || !profiles.team || !teamAbbr) return null;
  return profiles.team[teamAbbr] || null;
}
