// api/profiles.js — Load pre-computed play-by-play analytics profiles
// These are generated by the Python analysis pipeline from nflfastR data.

const PROFILE_URLS = {
  qb: 'data/qb_profiles.json',
  receiver: 'data/receiver_profiles.json',
  rb: 'data/rb_profiles.json',
  team: 'data/team_profiles.json',
};

const profileCache = {};

async function fetchProfile(key) {
  if (profileCache[key]) return profileCache[key];
  try {
    const res = await fetch(PROFILE_URLS[key]);
    if (!res.ok) return {};
    const data = await res.json();
    profileCache[key] = data;
    return data;
  } catch (e) {
    console.warn(`Failed to load ${key} profiles:`, e);
    return {};
  }
}

export async function loadAllProfiles() {
  const [qb, receiver, rb, team] = await Promise.all([
    fetchProfile('qb'),
    fetchProfile('receiver'),
    fetchProfile('rb'),
    fetchProfile('team'),
  ]);
  return { qb, receiver, rb, team };
}

export function getPlayerProfile(profiles, playerName, position) {
  if (!profiles || !playerName) return null;
  // Try exact match first
  if (position === 'QB' && profiles.qb && profiles.qb[playerName]) {
    return { ...profiles.qb[playerName], profileType: 'qb' };
  }
  if ((position === 'WR' || position === 'TE') && profiles.receiver && profiles.receiver[playerName]) {
    return { ...profiles.receiver[playerName], profileType: 'receiver' };
  }
  if (position === 'RB' && profiles.rb && profiles.rb[playerName]) {
    return { ...profiles.rb[playerName], profileType: 'rb' };
  }
  // Fallback: search all profile sets
  for (const [type, data] of Object.entries(profiles)) {
    if (type === 'team') continue;
    if (data && data[playerName]) {
      return { ...data[playerName], profileType: type };
    }
  }
  return null;
}

export function getTeamProfile(profiles, teamAbbr) {
  if (!profiles || !profiles.team || !teamAbbr) return null;
  return profiles.team[teamAbbr] || null;
}
